name: flutterbyte
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^9.2.0
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.2
  flutter_animate: ^4.1.0
  intl: ^0.19.0
  lottie: ^3.1.2
  get: ^4.6.5
  shimmer: ^3.0.0
  url_launcher: ^6.3.0
  flutter_localizations:
    sdk: flutter
  visibility_detector: ^0.4.0+2

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.2.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.jpeg"  
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: "#FFFFFF"
  adaptive_icon_background: "#FFFFFF"


flutter:
  uses-material-design: true
  generate: true 



  assets:
    - assets/logo/
    - assets/images/
    - assets/images/committee/ 
    - assets/images/speakers/   
    - assets/dump/ 
    - assets/lottie/
    - assets/svg/
    - assets/fonts/

  fonts:
    - family: Abel
      fonts:
        - asset: assets/fonts/Abel-Regular.ttf
 
